### ISSUE TITLE
Since you made a spam open box for the new box, can you make hacks for the new game mode?

### ISSUE THREAD

**Issue by sdkhfgvwierg** [DummyPotato/Potato-Scripts-2.0#2]
Look at title!

**Comment by DummyPotato** [comment]
I can try, if all answers are correct for the set when you are playing on the new gamemode I can do that. I wasn't able to figure out how to make all answers correct.

**Comment by DummyPotato** [comment]
Btw what I meant in the previous comment is a script that answers for you, selects a power up for you (or whatever it is called) and randomly moves around. If you would like something different lmk

**Comment by sdkhfgvwierg** [comment]
Thanks.

**Comment by sdkhfgvwierg** [comment]
When I say these thing I don't mean "I don't like what you already did but what I want" these are just ideas ok, I'm not trying to be like demanding when I say these things.

**Comment by sdkhfgvwierg** [comment]
Mabye you could add like a set points book mark or you could make a menu and put all the things you make on it.

**Comment by sdkhfgvwierg** [comment]
You could mabye add something on the menu that lets you max out your abilities or like the power ups you can choose.

**Comment by sdkhfgvwierg** [comment]
You could also add to where it lets you choose an ability that you want other than whats on the choices.

**Comment by sdkhfgvwierg** [comment]
These are all ideas for you.

**Comment by Apersonvr** [comment]
They are pretty cool ideas

**Comment by sdkhfgvwierg** [comment]
Thank you!

**Comment by DummyPotato** [comment]
I'll try to see what I can do!

**Comment by sdkhfgvwierg** [comment]
Thank you so much!

**Comment by DummyPotato** [comment]
It looks like some of it isn't managed client side, which means I will not be able to make a script for it. Maybe, there is a way but I am not that advanced at coding yet. I recommend opening an issue in glizzy's hacks and see what he can do for you :)

**Comment by sdkhfgvwierg** [comment]
Thank you!
