### ISSUE TITLE
Did you star me?

### ISSUE THREAD

**Issue by YaBoyMH** [DummyPotato/Potato-Scripts-2.0#6]
I'm just curious. Also if you did thank you very much I also have you stared and followed!

**Comment by YaBoyMH** [comment]
I can close out this issue if you would like!

**Comment by YaBoyMH** [comment]
Also I will kindly delete your stuff if you would like me too. But if you haven't read the read me make sure to read that!

**Comment by DummyPotato** [comment]
ye, i did star this :)
